# Use the custom base image created earlier
FROM ros_galactic_with_deps

# Set environment variables
ENV ROS_WS=/ros2_ws
ENV ROS_DOMAIN_ID=56

# Copy requirements.txt and install Python dependencies
COPY requirements.txt .
RUN pip3 install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt


# This image will have all the base dependencies plus the Python packages installed
